Part 1

In [1]:
numbers = []
for x in range(15):
    numbers.append(1)

In [2]:
sevens = []
for x in range(15):
    sevens.append(7)

In [3]:
numbers = []
for x in range(100, 151):
    numbers.append(x)

In [4]:
evens = []
for x in range(0, 101):
    if x % 2 == 0:
        evens.append(x)

In [5]:
years = []
for x in range(1950, 2021):
    if x % 4 == 0:
        years.append(x)

Part 2 - NumPy

In [6]:
import numpy as np

In [7]:
data = np.zeros(15)

In [8]:
array = np.ones(15)

In [9]:
array = np.full(15, 7)

In [10]:
array = np.arange(100, 151, 1)

In [11]:
array = np.arange(1900, 2022, 1)

In [12]:
array = np.arange(0, 101, 2)

# another way would be:

numbers = np.arange(0, 101)
evens = numbers[numbers % 2 == 0]

In [13]:
array = np.arange(1950, 2021)
filtered = array[array % 4 == 0]

Overall, default python was more comfortable as I am familiar with the syntax.

Otherwise, NumPy seems faster and easier to code, just needs a little more practice

Part 3 - NumPy matrices

In [14]:
%load_ext numpy_html

In [15]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

In [16]:
data = np.arange(1, 50)
data = data.reshape(7, 7)
data

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [17]:
data = np.random.randint(0, 6, 64)
data = data.reshape(8, 8)
data

array([[1, 4, 2, 1, 2, 4, 4, 5],
       [3, 1, 4, 3, 0, 3, 1, 4],
       [2, 1, 0, 4, 3, 5, 1, 3],
       [3, 5, 0, 1, 1, 2, 2, 2],
       [3, 5, 5, 2, 4, 5, 4, 1],
       [2, 2, 2, 1, 0, 3, 4, 2],
       [5, 5, 3, 2, 1, 3, 0, 4],
       [1, 2, 5, 2, 0, 3, 0, 2]])

In [18]:
data = np.random.randint(3)
data = np.random.randn(8, 8)
data

array([[ 1.53608261, -0.72017781, -0.35615554,  0.26897764, -1.87497345,
        -0.17857922, -0.36136831, -0.50093502],
       [ 1.28783245,  0.10777679, -1.01885638, -1.30523433, -0.99879923,
        -0.8462765 , -0.33753198,  0.20010124],
       [ 0.40429753,  0.35536885,  0.5292413 , -1.05795096, -1.20136017,
        -0.19937222,  1.10387377,  0.5084386 ],
       [ 0.64649497, -0.69502606, -0.85084666,  1.31638093,  1.27081272,
        -1.35058899, -1.82459501,  0.23179232],
       [-1.3592066 ,  0.37845741,  1.01246688,  0.56672864,  1.24254651,
        -0.07910387,  1.74723214, -0.95392082],
       [ 1.63433344,  1.11308758, -0.23549717,  0.42714497, -0.62750221,
         0.84167913,  1.55796576, -0.98279838],
       [-1.2267799 , -1.12736309, -1.66789999,  0.21965061,  1.7693892 ,
        -1.3824427 ,  0.85737941, -0.58836705],
       [ 0.51158539,  0.12964109, -0.59681838, -0.48962801, -0.48987007,
        -0.83167351,  0.97498376, -0.17745335]])

Part 4

In [19]:
data = np.linspace(0, 1, 10)
data

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [20]:
data = np.linspace(0, 5, 100)
data = data.reshape(10, 10)
data

array([[0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
        0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545],
       [0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
        0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596],
       [1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
        1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646],
       [1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
        1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697],
       [2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
        2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747],
       [2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
        2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798],
       [3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
        3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848],
       [3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737374,
        3.78787879, 3.83838384, 3.88888889, 3.93939394, 3.98989899],
       [4.04040404, 4.09090909, 4.14141414, 4.19191919, 4.24242424,
        4.29292929, 4.34343434, 4.39393939, 4.44444444, 4.49494949],
       [4.54545455, 4.5959596 , 4.64646465, 4.6969697 , 4.74747475,
        4.7979798 , 4.84848485, 4.8989899 , 4.94949495, 5.        ]])

Part 5

In [21]:
set1 = [23, 34, 54, 31, 75]
set2 = [33, 56, 78, 65, 97]
set3 = [41, 32, 11, 39, 51]
matrix = [set1, set2, set3]
matrix = np.array(matrix)
matrix

array([[23, 34, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

In [22]:
data = np.arange(128, 256, 1)
data = data.reshape(8, 16)
data

array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

In [23]:
data = np.arange(0.05, 5.05, 0.05)
data = data.reshape(10,10)
data

array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

Part 6

In [24]:
dataset = np.arange(1, 37).reshape(6, 6)
dataset

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [25]:
data = dataset[3:,2:]
data

array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

In [26]:
data = dataset[:4, 3]
data

array([ 4, 10, 16, 22])

In [27]:
data = dataset[2]
data

array([13, 14, 15, 16, 17, 18])

In [28]:
data = dataset[3:]
data

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

Part 7

In [29]:
dataset = np.arange(1, 50).reshape(7, 7)
dataset

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [30]:
dataset += 50
dataset

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [31]:
total = np.sum(dataset)
total

3675

In [32]:
odds = dataset[dataset % 2 != 0]
total = np.sum(odds)
total

1875

In [33]:
deviation = np.std(dataset)
deviation

14.142135623730951

In [34]:
total = np.sum(dataset, axis=1)
total

array([378, 427, 476, 525, 574, 623, 672])

In [35]:
total = np.sum(dataset, axis=0)
total

array([504, 511, 518, 525, 532, 539, 546])